<?php

function ifoam_regulation_guidelines_menu() {
  $items = [];

  $items['regulation-guidelines-api'] = [
    'access callback' => true,
    'page callback' => 'ifoam_regulation_guidelines_api',
    'delivery callback' => 'drupal_json_output',
  ];

  return $items;
}

function ifoam_regulation_guidelines_api() {
  $action = ifoam_regulation_guidelines_getparam_action();
  $params = [
    'email' => ifoam_regulation_guidelines_getparam_email(),
  ];

  $api = new IformaRegulationGuidelinesApi();
  $response = $api->process($action, $params);

  drupal_json_output($response);
}

function ifoam_regulation_guidelines_getparam_action() {
  $params = drupal_get_query_parameters();
  if (array_key_exists('action', $params)) {
    return $params['action'];
  }
  else {
    return '';
  }
}

function ifoam_regulation_guidelines_getparam_email() {
  $params = drupal_get_query_parameters();
  if (array_key_exists('email', $params)) {
    return $params['email'];
  }
  else {
    return '';
  }
}
